version: 1
disable_existing_loggers: False
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: basic
formatters:
  basic:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
